### ISSUE TITLE
"could not be cloned." Error when starting database

### ISSUE THREAD

**Issue by seveibar** [seamapi/ava-postgres#22]
Possibly due to change in AVA?

Standard bootstrap, nothing special:

![image](https://github.com/seamapi/ava-postgres/assets/1910070/e8a9d89b-aeb9-4fdc-9d1e-f2558fd9b3c1)

![image](https://github.com/seamapi/ava-postgres/assets/1910070/f1554296-b85f-4783-bbbf-1ad84cb22a47)

**Comment by seveibar** [comment]
syntax is `getTestDatabase` not `getTestDatabase(t)`

**Comment by codetheweb** [comment]
I think strict types protect against this :)
